/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DisruptorRouteImport } from './routes/disruptor'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as LineupRouteImport } from './routes/lineup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptorRoute = DisruptorRouteImport.update({
  id: '/disruptor',
  path: '/disruptor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupRoute = LineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/disruptor': typeof DisruptorRoute
  '/intel': typeof IntelRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/disruptor': typeof DisruptorRoute
  '/intel': typeof IntelRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases': typeof CasesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/disruptor': typeof DisruptorRoute
  '/intel': typeof IntelRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/disruptor'
    | '/intel'
    | '/lineup'
    | '/login'
    | '/ops'
    | '/cases/$caseId'
    | '/cases/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/disruptor'
    | '/intel'
    | '/lineup'
    | '/login'
    | '/ops'
    | '/cases/$caseId'
    | '/cases'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/disruptor'
    | '/intel'
    | '/lineup'
    | '/login'
    | '/ops'
    | '/cases/$caseId'
    | '/cases/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DisruptorRoute: typeof DisruptorRoute
  IntelRoute: typeof IntelRoute
  LineupRoute: typeof LineupRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptor': {
      id: '/disruptor'
      path: '/disruptor'
      fullPath: '/disruptor'
      preLoaderRoute: typeof DisruptorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup': {
      id: '/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof LineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DisruptorRoute: DisruptorRoute,
  IntelRoute: IntelRoute,
  LineupRoute: LineupRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
